.TH mexec 1 "17 September 2026" "Version 1.0"

.SH NAME
mexec - my exec, creates a pipeline of commands

.SH SYNOPSIS
mexec [FILE]

.SH DESCRIPTION
Executes a list of commands where standard output (stdout) from the previous
command is piped to standard input (stdin) of the next command.
Commands are read from stdin by default, or optionally from a
.I FILE
passed as an argument to
.BR mexec .
.PP
Each input line is considered a command line with space-separated arguments.
Command lines shall not be longer than 1024 bytes each.
Empty lines and quotation marks are not supported.

.SH SOLUTION
Command lines are read from an input stream, either from stdin or from an open
file. Each command line is parsed into an array of arguments, where the first
element is the command itself and the rest of the elements are arguments for the
command. The first parsed command line is stored, then next command
line is parsed and a pipe is created with the pipe() system call. This pipe is
the output pipe for the previous command and the input pipe for the next command.
When the output pipe has been created the previous command is executed with the
read end of the input pipe attached to stdin for the command process, using the
dup2() system call, and the write end of the output pipe is attached to stdout
for the command process. For the very first command in the pipeline there is
no input pipe and stdin remains unaltered instead. The next command is read and
a pipe between previous and next command is created while there are commands to
read. The final command is executed with the read end of its input pipe attach
to stdin of the command process and stdout of the command process remaining
unaltered.
Once the whole pipeline has been set up, the main process waits for all child
command processes to terminate before exiting.
.PP
Executing a command is done by forkinging the process with the fork() system
call. In the child process the read end of the input pipe is attached to the
file descriptor for stdin, with the dup2() system call, and the write end of
the output pipe is attached to the file descriptor for stdout. Then the command
is executed with execvp() by passing the command argument array point.
.PP
Error handling of any failed library or system call is done by manually freeing
any allocated resources (memory pointers or file descriptors) and exiting directly
with appropriat exit status code or jumping to waiting for child processes if
there is a possibility that any child process may have been spawned at that point
in the code.

.SS Main algorithm
.IP "1. Let stdin file descriptor represent read end of input pipe"
.IP "2. Read and parse first command"
.IP "3. While there are commands left to read:"
.RS
.IP "3.1 Read and parse next command"
.IP "3.2 Create output pipe"
.IP "3.3 Execute previous command"
.RS
.IP "3.3.1 Fork process"
In child process:
.RS
.IP "3.3.1.1 Duplicate read end of input pipe on to stdin file descriptor (dup2())"
.IP "3.3.1.2 Duplicate write end of output pipe on to stdout file descriptor (dup2())"
.IP "3.3.1.2 exec() parsed argument list for previous command (execvp())"
.RE
.RE
.IP "3.4 Close read end of input pipe"
.IP "3.5 Close write end of output pipe"
.IP "3.6 Designate the output pipe as the new input pipe"
Store file descriptor for read end of output pipe as read end of new input pipe.
Overwriting the file descriptor for the read end of the previous input pipe (which was closed in 3.4).
.RE
.IP "4. Execute the last parsed command."
    (See 3.3)
    With file descriptor for stdout instead of write end of output pipe.
.IP "5. Wait for all child processes to terminate (wait())"
.IP "6. Exit with appropriate exit code"
.PP

.SH EXIT STATUS
.IP 0
    Successful pipeline execution and all commands terminated with code 0
.IP 1
    An error occured
.IP "<child exit code>"
    The return code from a command, if pipeline executed successfully but at least
    one command exited with non-zero return code.
.IP "128 + <signal number>"
    If pipeline executed successfully but a command was terminated by a signal.
    Exit status is the signal number added to the constant 128.
    Could also mean that
.BR mexec " itself was terminated by a signal."
.PP
In case multiple commands returned non-zero exit code or were terminated by a signal
it is indeterminate which code was propagated as the exit status.
.PP
Note that it may not be possible to distinguish between a child exit code 1 or
an error setting up the pipeline. Likewise it may also not be possible to
distinguish between a child exit code larger than 128 and a signal termination code.

.SH AUTHORS
Aleksander Zdunek <redacted>@cs.umu.se

This program was an assignment for the course Systemnära Programmering 5DV254 at UMU.
