.TH mexec 1 "TODO: update date 15 August 2026" "Version 0.x"

.SH NAME
mexec - my exec, creates a pipeline of commands

.SH SYNOPSIS
mexec [FILE]

.SH DESCRIPTION
TODO

.SH SOLUTION
TODO
lorem ipsum dolor
.br
sit amet consectitur

.SH EXIT STATUS
.IP 0
    Successful pipeline execution
.IP 1
    Something went wrong
TODO: other exit codes?

.SH AUTHORS
Aleksander Zdunek TODO: add username
.br
This program was an assignment for the course Systemnära Programmering 5DV254 at UMU.
